name: encrypta
description: "A secure document cryptography application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8

  # Firebase Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_app_check: ^0.2.2

  # File Handling & Storage
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.1
  image: ^4.1.3
  pdf: ^3.11.3

  # Platform & Utils
  permission_handler: ^11.4.0
  pull_to_refresh: ^2.0.0
  flutter_isolate: ^2.1.0
  uuid: ^4.5.1
  open_file: ^3.3.2
  pdf_render: ^1.4.2
  path: ^1.8.3
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
