// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWKPCqH9d7Am5tgnRiXBuT6GMFwkLm9Q',
    appId: '1:900980711359:web:3945bf5c4119b7f523cb0a',
    messagingSenderId: '900980711359',
    projectId: 'clone-insta-1c836',
    authDomain: 'clone-insta-1c836.firebaseapp.com',
    storageBucket: 'clone-insta-1c836.appspot.com',
    measurementId: 'G-Y2HHY7Y6HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8CN3FkOVGO-0NNVTUpXgKbMqhakTU8PI',
    appId: '1:900980711359:android:fa17e5bdb6a5ca5823cb0a',
    messagingSenderId: '900980711359',
    projectId: 'clone-insta-1c836',
    storageBucket: 'clone-insta-1c836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBHa6xN4VgA060pWqyjcwwEuGKIee6Qvo',
    appId: '1:900980711359:ios:0a556ab85ac4786223cb0a',
    messagingSenderId: '900980711359',
    projectId: 'clone-insta-1c836',
    storageBucket: 'clone-insta-1c836.appspot.com',
    iosBundleId: 'com.example.encrypta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBHa6xN4VgA060pWqyjcwwEuGKIee6Qvo',
    appId: '1:900980711359:ios:0a556ab85ac4786223cb0a',
    messagingSenderId: '900980711359',
    projectId: 'clone-insta-1c836',
    storageBucket: 'clone-insta-1c836.appspot.com',
    iosBundleId: 'com.example.encrypta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxWKPCqH9d7Am5tgnRiXBuT6GMFwkLm9Q',
    appId: '1:900980711359:web:3945bf5c4119b7f523cb0a',
    messagingSenderId: '900980711359',
    projectId: 'clone-insta-1c836',
    authDomain: 'clone-insta-1c836.firebaseapp.com',
    storageBucket: 'clone-insta-1c836.appspot.com',
    measurementId: 'G-Y2HHY7Y6HE',
  );
}
